---
deployment:
  tasks:
    - export DEPLOYPATH=/home/darvigmolascom/public_html
    - /bin/cp index.html "$DEPLOYPATH"
    - /bin/cp landing.html "$DEPLOYPATH"
    - /bin/cp produtos.html "$DEPLOYPATH"
    - /bin/cp .htaccess "$DEPLOYPATH"
    - /bin/cp -R assets "$DEPLOYPATH"
    - /bin/cp -R painel "$DEPLOYPATH"
